#pragma once

#include <cstdint>
#include <limits>
#include <compare>
#include <vector>
#include <string>

#include "Index.h"

namespace clice {
class Compiler;
}

namespace clice::index {

/// This defines the structures that directly generated by the indexer.
/// It could be used to serialized to other formats like binary or JSON.
namespace memory {

using Symbol = index::Symbol<std::string, std::vector>;

using Index = index::Index<std::string, std::vector>;

}  // namespace memory

/// index the given translation unit.
memory::Index index(Compiler& compiler);

}  // namespace clice::index
